import type { Metadata } from 'next';
import { Open_Sans, Parkinsans } from 'next/font/google';
import './globals.css';
import NavBar from '@/components/layout/NavBar';
import Footer from '@/components/layout/Footer';
import { UserProvider } from '@auth0/nextjs-auth0/client';

export const metadata: Metadata = {
  title: 'Omakatse',
  description: 'Generated by create next app'
};

const openSans = Open_Sans({
  subsets: ['latin'], // Specify character subsets
  weight: ['400', '700'], // Specify font weights
  variable: '--font-open-sans' // Specify custom variable name
});

const parkinsans = Parkinsans({
  subsets: ['latin'], // Specify character subsets
  weight: ['400', '700'], // Specify font weights
  variable: '--font-parkinsans' // Specify custom variable name
});

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="no-scrollbar">
      <UserProvider>
        <body
          className={`${openSans.variable} ${parkinsans.variable} flex min-h-screen flex-col overflow-auto overflow-x-hidden bg-gray-50 antialiased`}
        >
          <NavBar />
          <div className="flex flex-grow justify-center">{children}</div>
          <Footer />
        </body>
      </UserProvider>
    </html>
  );
}
