import type { Metadata } from "next";
import { Open_Sans, Parkinsans } from "next/font/google";
import "./globals.css";
import NavBar from "@/components/NavBar";

export const metadata: Metadata = {
  title: "Omakatse",
  description: "Generated by create next app",
};

const openSans = Open_Sans({
  subsets: ["latin"], // Specify character subsets
  weight: ["400", "700"], // Specify font weights
  variable: "--font-open-sans", // Specify custom variable name
});

const parkinsans = Parkinsans({
  subsets: ["latin"], // Specify character subsets
  weight: ["400", "700"], // Specify font weights
  variable: "--font-parkinsans", // Specify custom variable name
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${openSans.variable} ${parkinsans.variable} antialiased mt-36 px-20`}
      >
        <NavBar />
        {children}
      </body>
    </html>
  );
}
