import type { Metadata } from "next";
import { Open_Sans, Parkinsans } from "next/font/google";
import "./globals.css";
import NavBar from "@/components/layout/NavBar";
import Footer from "@/components/layout/Footer";

export const metadata: Metadata = {
  title: "Omakatse",
  description: "Generated by create next app",
};

const openSans = Open_Sans({
  subsets: ["latin"], // Specify character subsets
  weight: ["400", "700"], // Specify font weights
  variable: "--font-open-sans", // Specify custom variable name
});

const parkinsans = Parkinsans({
  subsets: ["latin"], // Specify character subsets
  weight: ["400", "700"], // Specify font weights
  variable: "--font-parkinsans", // Specify custom variable name
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${openSans.variable} ${parkinsans.variable} overflow-auto overflow-x-hidden`}
      >
        <NavBar />
        <div className="mt-32">
        {children}
        </div>
        <Footer />
      </body>
    </html>
  );
}
